def smartNumber(n: int) -> int:
    """
    Find the n-th 'smart number'.
    A smart number is defined as a number whose digits in base 16
    (hexadecimal representation) contain only the digits 0, 2, 4, 6, 8, A (10).
    Essentially, smart numbers are numbers whose hexadecimal representation
    consists only of even hex digits (including 'A' which represents 10).

    The sequence starts: 30 (16^1 + 4*16^0? Wait, let's verify the pattern).

    Actually, looking at the examples:
    1st: 30
    50th: 273
    1000th: 2664

    Let's reconsider the definition based on the examples.
    If we map the smart numbers to a base-6 system using digits [0, 2, 4, 6, 8, A] but wait, 
    30 in decimal is 1E in hex. That doesn't look like only even digits.

    Let's try a different interpretation. Maybe the "smart numbers" are numbers formed 
    by digits {0, 1, 2, 3, 4, 5} in base 6, but interpreted as decimal?
    No, 30 is the 1st.

    Let's look at the mapping:
    If smart numbers are generated by treating n as a number in base 6 and mapping 
    digits to {0, 2, 4, 6, 8, A} in hex?
    n=1 -> base6 "1" -> map to '2'? No, result is 30.

    Alternative hypothesis:
    Smart numbers are numbers whose hexadecimal digits are only from {2, 4, 6, 8, A, C, E}? 
    Or maybe {0, 2, 4, 6, 8, A} where A=10?

    Let's try to reverse engineer from 30.
    If the 1st smart number is 30.
    If the sequence is based on powers of 2? 30 is not a power of 2.

    Let's try: Smart numbers are numbers x such that x = sum(d_i * 2^(i+1)) where d_i is in {0,1}?
    No.

    Let's try the mapping where we take n, convert to base 6, and map digits 0-5 to 
    hex digits 2, 4, 6, 8, A, C?
    n=1 -> base6: 1 -> map to '4'? Value 4. Not 30.
    n=1 -> map to 30?

    Maybe the digits allowed in hex are {2, 4, 6, 8, A, C, E, ...} i.e. even hex digits.
    Hex digits: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F.
    Even values: 0, 2, 4, 6, 8, A(10), C(12), E(14). Total 8 digits.

    If we generate numbers using only even hex digits, ordered numerically:
    1st: 0? Usually 0 is not counted or 1st non-zero?
    If 0 is skipped:
    1st: 2 (hex 2) = 2. No, we need 30.

    Wait, 30 in hex is 1E. E is 14 (even). 1 is odd. So 1E has an odd digit.
    This contradicts "only even hex digits".

    Let's re-read the values.
    1 -> 30
    50 -> 273
    1000 -> 2664

    Is it possible the digits are in base 6, but the values are specific?
    Let's check if the sequence is simply 2 * (n-th number with digits 0,1 in base 2 interpreted as hex)?
    No.

    Let's try: The smart numbers are formed by the digits 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F?
    No, that's too many.

    What if "smart number" means the number whose hexadecimal representation, when converted 
    to decimal, has a property?

    Let's try to fit a formula.
    f(1) = 30
    f(50) = 273
    f(1000) = 2664

    Difference 1->50: +243. Diff 50->1000: +2391.

    Maybe it's related to base 6?
    Let's assume the set of digits is {0, 2, 4, 6, 8, A}. Size 6.
    If we interpret n in base 6, and map digits 0->0, 1->2, 2->4, 3->6, 4->8, 5->A.
    Then interpret the result as a hex number.
    n=1 -> base6 "1" -> map to '2'. Hex "2" = 2. Not 30.

    What if we skip 0?
    Digits: 2, 4, 6, 8, A, C? (Size 6).
    Map 1->2, 2->4, ... 6->C?
    n=1 -> 2.

    What if the first smart number is actually 30 (decimal) which is 0x1E?
    Digits 1, E. 1 is odd. E is even.

    Let's try another angle.
    Maybe the digits allowed are {0, 1, 2, 3, 4, 5} in base 6, but the value is calculated differently?

    Wait, look at 30. In base 6, 30 is 50 (5*6 + 0).
    Look at 273. 273 in base 6: 273 / 6 = 45 r 3. 45 / 6 = 7 r 3. 7 / 6 = 1 r 1. -> 1133_6.
    Look at 2664. 2664 in base 6: 
    2664 / 6 = 444 r 0
    444 / 6 = 74 r 0
    74 / 6 = 12 r 2
    12 / 6 = 2 r 0
    2 / 6 = 0 r 2
    -> 20200_6.

    This doesn't show an obvious pattern of "digits 0-5".

    Let's try Base 5?
    30 in base 5: 110 (1*25 + 1*5). Digits 1, 1, 0.
    273 in base 5: 273 = 2*125 + 2*25 + 2*5 + 3? No. 
    273 / 5 = 54 r 3
    54 / 5 = 10 r 4
    10 / 5 = 2 r 0
    2 / 5 = 0 r 2
    -> 2043_5.

    Let's reconsider the problem statement. "Smart number".
    Maybe it's numbers that are multiples of something?
    30, 273, 2664.
    GCD(30, 273) = 3. GCD(3, 2664) = 3.

    What if we consider the sequence of numbers that can be represented using only the digits {0, 2, 4, 6, 8} in base 10?
    1st: 2
    2nd: 4
    ...
    6th: 20
    7th: 22
    ...
    This would generate 2, 4, 6, 8, 20, 22...
    Is 30 in this list? Yes, 3rd digit is 3, wait. Digits allowed 0,2,4,6,8.
    Numbers: 2, 4, 6, 8, 20, 22, 24, 26, 28, 40...
    30 contains '3', not allowed.

    What if the digits are {0, 1, 2, 3, 4, 5} in base 6, but we treat them as hex?
    Sequence:
    1 -> 1 (hex) = 1
    2 -> 2
    ...
    6 -> 6 (hex) = 6
    7 -> 10 (hex) = 16
    ...
    We need 1st = 30.

    Maybe the mapping is shifted?
    If n=1 corresponds to the string "30" in some base? No.

    Let's try to find a mapping f: N -> Int such that:
    f(1) = 30
    f(50) = 273
    f(1000) = 2664

    Let's check the differences again.
    273 - 30 = 243.
    2664 - 273 = 2391.

    Is it possible the smart numbers are defined as:
    Take n, write in base 6. Replace digits with values.
    What if the allowed digits are {0, 2, 4, 6, 8, A}?
    And we map n (in base 6) directly to hex string?
    But n=1 -> base6 "1". If we map 1->A? Then A=10. No.

    Wait, could it be that the "smart numbers" are numbers whose base-6 representation contains only the digits 0, 1, 2, 3, 4, 5 (which is all of them), but we are looking for something else?

    Let's try: Base 2, but digits mapped to 0, 1, 2, 3, 4, 5?

    Let's assume the question implies:
    Smart numbers are numbers whose hexadecimal digits are {0, 2, 4, 6, 8, A}.
    But we established 30 (0x1E) has a '1'.
    Unless the assertion is wrong and I should derive the logic.
    BUT I must satisfy the assertions.

    Maybe 30 is not 0x1E?
    Is it possible the base is different?
    Base 7? 30 in base 7 is 42.
    Base 8? 30 in octal is 36.
    Base 9? 30 in base 9 is 33.
    Base 10? 30.
    Base 11? 28 (2*11+8).

    Let's try a completely different approach.
    Maybe the "smart number" is the n-th number in the sequence of numbers that can be formed by the digits 0, 2, 4, 6, 8 in base 10, but including something else?

    Wait, what if the digits allowed are {0, 1, 2, 3, 4, 5} and the base is 6, but we output the decimal value of the number interpreted in base 6?
    Sequence: 0, 1, 2, 3, 4, 5, 10, 11... (base 6)
    Values: 0, 1, 2, 3, 4, 5, 6, 7... This is just natural numbers.

    What if the digits allowed are {0, 2, 4, 6, 8, A} (6 digits) and we form numbers in base 16?
    Sorted list of such numbers:
    0, 2, 4, 6, 8, A, 20, 22, 24, 26, 28, 2A, 40...
    1st non-zero? If 0 is skipped: 1st=2.
    We need 1st=30.

    Maybe the set of digits is {3, 0, ...}?

    Let's look at the numbers 30, 273, 2664 again.
    30 = 2 + 2*16? No.
    30 = 3*10.
    273 = 3*91.
    26