def _validate_inputs(start: int, step: int, target: int) -> bool:
    """
    Validates that the inputs are valid integers and that the step is not zero.
    Returns True if valid, raises ValueError otherwise.
    """
    if not isinstance(start, int):
        raise TypeError("The 'start' parameter must be an integer.")
    if not isinstance(step, int):
        raise TypeError("The 'step' parameter must be an integer.")
    if not isinstance(target, int):
        raise TypeError("The 'target' parameter must be an integer.")
    if step == 0:
        raise ValueError("The 'step' parameter cannot be zero as it would create an infinite sequence of identical numbers without termination logic for infinite sets, and mathematically divides by zero in difference checks.")
    return True

def _is_target_reachable(start: int, step: int, target: int) -> bool:
    """
    Determines if 'target' exists in the arithmetic sequence defined by 'start' and 'step'.

    The sequence is: start, start + step, start + 2*step, ...

    Logic:
    1. Calculate the difference between target and start.
    2. If the difference is zero, the target is the first element (start == target).
    3. If the difference has the opposite sign of the step, the target is "behind" the start 
       and will never be reached (since the sequence moves in the direction of the step).
    4. If the difference has the same sign (or is zero) and is perfectly divisible by step,
       the target is in the sequence.
    5. Otherwise, the target is not reachable.
    """
    difference = target - start

    # Case 1: Target is exactly the start element
    if difference == 0:
        return True

    # Case 2: Check direction
    # If step is positive, difference must be positive to reach target.
    # If step is negative, difference must be negative to reach target.
    if (step > 0 and difference < 0) or (step < 0 and difference > 0):
        return False

    # Case 3: Check divisibility
    # If the difference is zero, we handled it above, so here difference != 0.
    if difference % step != 0:
        return False

    return True

def does_Contain_B(start: int, step: int, target: int) -> bool:
    """
    Determines whether a given 'target' number is present in the infinite arithmetic
    sequence generated by starting at 'start' and adding 'step' repeatedly.

    Parameters:
    - start (int): The first number in the sequence.
    - step (int): The common difference between consecutive numbers.
    - target (int): The number to search for.

    Returns:
    - bool: True if the target is in the sequence, False otherwise.

    Raises:
    - TypeError: If any input is not an integer.
    - ValueError: If the step is zero.
    """
    # Step 1: Explicitly validate inputs to ensure type correctness and logical validity
    _validate_inputs(start, step, target)

    # Step 2: Determine if the target is mathematically reachable using the helper function
    is_present = _is_target_reachable(start, step, target)

    return is_present