import re
from typing import List, Optional


def _normalize_string_for_comparison(value: str, base_pattern: str) -> Optional[str]:
    """
    Normalize a string by replacing all substrings that match the base pattern
    with a placeholder token '#', while preserving the length of the original
    matched substring. If the string cannot be fully normalized (i.e., it contains
    characters that do not match the pattern structure), return None.

    This function assumes that the 'base_pattern' is a string representing a
    single abstract symbol (like 'a', 'b', etc.). We are checking if the input
    'value' is consistent with the idea that all occurrences of this base_pattern
    in a normalized sequence must be replaced by the same placeholder.

    However, the core logic here is slightly different based on the problem's
    nature: we need to ensure that the sequence of *types* of elements in the
    first list matches the sequence of *types* in the second list, where the
    "type" is defined by whether elements are identical or different from each
    other within their respective groups in the pattern.

    Actually, re-evaluating the problem based on the assertions:
    - ["red","green","green"] vs ["a", "b", "b"] -> True. Here 'red' maps to 'a',
      and the two 'green's map to the two 'b's. The pattern is about the sequence
      of uniqueness.
    - ["red","green","greenn"] vs ["a","b","b"] -> False. 'red' is unique (a).
      The last two strings 'green' and 'greenn' are different strings, so they
      cannot map to the same pattern symbol 'b'. Hence False.
    - ["red","green","greenn"] vs ["a","b"] -> False. The input has 3 elements,
      pattern has 2. Length mismatch immediately fails.

    Therefore, the logic is:
    1. The two lists must have the same length.
    2. We must partition the first list into equivalence groups where each group
       contains only identical strings.
    3. We must partition the second list into equivalence groups where each group
       contains only identical strings.
    4. The sequence of group hashes (or types) must be identical.
       For example, if the first list is [A, B, B], the groups are {A}, {B}.
       Sequence of types: [Type(A), Type(B)].
       Wait, that's not quite right. The example ["red", "green", "green"] maps to ["a", "b", "b"].
       This implies:
       Index 0: "red" (new) -> "a"
       Index 1: "green" (new) -> "b"
       Index 2: "green" (seen) -> "b"

       So the pattern is generated by scanning the list:
       - If current item is not seen before, assign a new pattern letter.
       - If current item was seen before, reuse the pattern letter.

       Then we do the same for the 'patterns' array and compare the generated sequences.

    Let's refine the helper to generate this pattern sequence.
    """

    if not isinstance(value, str):
        raise TypeError(f"Expected string input, got {type(value).__name__}")

    # We don't need to pass base_pattern here in the standard way because
    # the pattern generation is derived from the input list itself.
    # This helper seems misnamed for the specific task. Let's rethink the structure.
    # The previous thinking about 'normalize_string' was for a different problem (isomorphic strings).
    # For THIS problem, we need to convert the list of strings into a canonical pattern
    # string, and then compare those canonical patterns.

    pass


def _generate_pattern_sequence(sequence: List[str]) -> str:
    """
    Convert a list of strings into a pattern string (e.g., "a", "b", "c"...)
    based on the first occurrence of each unique string.

    Rules:
    - The first unique string encountered gets mapped to 'a'.
    - The second unique string encountered gets mapped to 'b'.
    - Subsequent occurrences of a string get mapped to the same letter as its first occurrence.

    If the list contains invalid types, raises TypeError.
    """
    if not isinstance(sequence, list):
        raise TypeError(f"Expected list of strings, got {type(sequence).__name__}")

    if len(sequence) == 0:
        return ""

    # Dictionary to map actual string values to their assigned pattern character
    value_to_pattern_char: dict[str, str] = {}
    # Counter for the next available pattern character
    next_char_code = ord('a')
    # List to store the generated pattern characters
    result_chars: List[str] = []

    for item in sequence:
        # Validate each item is a string
        if not isinstance(item, str):
            raise TypeError(f"All items in the sequence must be strings, found {type(item).__name__} at index {sequence.index(item)}")

        if item in value_to_pattern_char:
            # Reuse existing pattern character
            pattern_char = value_to_pattern_char[item]
        else:
            # Assign new pattern character
            pattern_char = chr(next_char_code)
            next_char_code += 1
            value_to_pattern_char[item] = pattern_char

        result_chars.append(pattern_char)

    return "".join(result_chars)


def _validate_inputs(pairs: List[str], patterns: List[str]) -> None:
    """
    Perform basic validation on the input lists.
    Raises ValueError if inputs are invalid.
    """
    if not isinstance(pairs, list):
        raise TypeError("First argument must be a list")

    if not isinstance(patterns, list):
        raise TypeError("Second argument must be a list")

    if len(pairs) == 0 or len(patterns) == 0:
        # Empty lists are technically valid inputs to the function, 
        # but they will result in empty patterns which are equal.
        # We do not raise an error for empty lists, they are handled by logic.
        pass

    # Check if all elements in 'pairs' are strings
    for i, item in enumerate(pairs):
        if not isinstance(item, str):
            raise TypeError(f"All elements in the first list must be strings. Element at index {i} is {type(item).__name__}")

    # Check if all elements in 'patterns' are strings
    for i, item in enumerate(patterns):
        if not isinstance(item, str):
            raise TypeError(f"All elements in the second list must be strings. Element at index {i} is {type(item).__name__}")


def is_samepatterns(pairs: List[str], patterns: List[str]) -> bool:
    """
    Check whether the sequence in 'pairs' follows the pattern defined in 'patterns'.

    Two sequences follow the same pattern if they have the same length and their
    elements correspond to the same abstract pattern structure.

    Example:
        pairs = ["red", "green", "green"]
        patterns = ["a", "b", "b"]
        Here, "red" is the first unique element ('a'), and "green" appears twice ('b').
        The pattern for 'pairs' is "abb". The pattern for 'patterns' is "abb". They match.

    Parameters:
        pairs: A list of strings representing the sequence to test.
        patterns: A list of strings representing the expected pattern structure.

    Returns:
        bool: True if 'pairs' follows the pattern of 'patterns', False otherwise.

    Raises:
        TypeError: If inputs are not lists or contain non-string elements.
        ValueError: If inputs are invalid in some other way (though currently mostly covered by TypeError).
    """
    # Step 1: Validate inputs explicitly
    _validate_inputs(pairs, patterns)

    # Step 2: Check for length equality
    # If lengths differ, the pattern cannot be followed.
    if len(pairs) != len(patterns):
        return False

    # Step 3: Generate the canonical pattern string for the 'pairs' list
    # e.g., ["red", "green", "green"] -> "abb"
    try:
        generated_pattern_for_pairs = _generate_pattern_sequence(pairs)
    except TypeError:
        # This should theoretically be caught by _validate_inputs, but defensive programming
        re-raises it just in case of unexpected internal changes.
        raise

    # Step 4: Generate the canonical pattern string for the 'patterns' list
    # e.g., ["a", "b", "b"] -> "abb"
    try:
        generated_pattern_for_input_patterns = _generate_pattern_sequence(patterns)
    except TypeError:
        # Defensive re-raise
        raise

    # Step 5: Compare the two generated pattern strings
    # If they are identical, the sequence follows the pattern.
    return generated_pattern_for_pairs == generated_pattern_for_input_patterns