import math

def is_num_keith(n: int) -> bool:
    """
    A Keith number (or repfigit number) is an integer n with k digits (k > 1) 
    that appears in a sequence generated by the sum of the previous k terms, 
    starting with the digits of n.

    Example: 197
    Digits are 1, 9, 7. (k=3)
    Sequence: 1, 9, 7, (1+9+7)=17, (9+7+17)=33, (7+17+33)=57, (17+33+57)=107, 
    (33+57+107)=197.
    Since 197 appears in the sequence, it is a Keith number.
    """
    # --- Input Validation ---
    # Check if the input is an integer
    if not isinstance(n, int):
        raise ValueError(f"Input must be an integer, received: {type(n)}")

    # Keith numbers are generally defined as positive integers.
    # Negative numbers and zero are not typically considered Keith numbers.
    if n <= 0:
        return False

    # --- Digit Extraction ---
    # Convert number to string to easily split into digits
    str_n = str(n)
    num_digits = len(str_n)

    # Keith numbers must have at least two digits (k > 1).
    # Single-digit numbers are technically not Keith numbers by standard definition.
    if num_digits < 2:
        return False

    # Create the initial sequence of digits as a list of integers
    # Example: 197 -> [1, 9, 7]
    initial_sequence = []
    for char in str_n:
        initial_sequence.append(int(char))

    # --- Sequence Generation ---
    # We continue generating terms until the current term is >= n.
    # If the term is exactly n, it is a Keith number.

    # Create a working copy of the sequence to avoid modifying the original 
    # if we needed it for debugging, though here we just need to iterate.
    current_sequence = list(initial_sequence)

    while True:
        # Calculate the sum of the last 'num_digits' terms
        # This is the Fibonacci-like step
        last_k_terms = current_sequence[-num_digits:]
        next_term = sum(last_k_terms)

        # Check if we found the number
        if next_term == n:
            return True

        # If the sequence exceeds n, n is not a Keith number
        if next_term > n:
            return False

        # Append the new term and continue
        current_sequence.append(next_term)

# Testing block to ensure functionality
if __name__ == "__main__":
    # Verification against provided assertions
    assert is_num_keith(14) == True
    assert is_num_keith(12) == False
    assert is_num_keith(197) == True