from typing import List

def moddiv_list(dividend_list: List[int], divisor_list: List[int]) -> List[int]:
    """
    Performs modulo division on two lists of integers using map and lambda.

    Args:
        dividend_list: A list of integers to be divided.
        divisor_list: A list of integers to divide by.

    Returns:
        A list of integers representing the result of (dividend % divisor) 
        for each pair of elements at the same index.

    Raises:
        ValueError: If the input lists have different lengths.
        ZeroDivisionError: If any element in divisor_list is zero.
        TypeError: If inputs are not lists or contain non-integer elements.
    """

    # Validate that inputs are actually lists
    if not isinstance(dividend_list, list) or not isinstance(divisor_list, list):
        raise TypeError("Both inputs must be lists.")

    # Validate that the lists are of equal length
    dividend_len = len(dividend_list)
    divisor_len = len(divisor_list)

    if dividend_len != divisor_len:
        raise ValueError(
            f"Input lists must have the same length. "
            f"Received: dividend={dividend_len}, divisor={divisor_len}"
        )

    # Handle the empty list edge case explicitly
    if dividend_len == 0:
        return []

    # Internal validation for integer types and zero divisors
    # While map/lambda is required for the core logic, we should 
    # pre-validate to ensure production-grade robustness.
    for i in range(dividend_len):
        val_dividend = dividend_list[i]
        val_divisor = divisor_list[i]

        if not isinstance(val_dividend, int) or not isinstance(val_divisor, int):
            raise TypeError(f"All elements in the lists must be integers. "
                            f"Found {type(val_dividend)} and {type(val_divisor)} at index {i}.")

        if val_divisor == 0:
            raise ZeroDivisionError(f"Division by zero encountered at index {i}.")

    # Core logic using map and lambda as requested.
    # zip combines the two lists into pairs: (dividend_0, divisor_0), (dividend_1, divisor_1)...
    # The lambda function takes each pair (a, b) and returns a % b.
    # map applies the lambda to every pair generated by zip.

    result_map_object = map(
        lambda pair: pair[0] % pair[1], 
        zip(dividend_list, divisor_list)
    )

    # Convert the map object back into a list to return
    result_list = list(result_map_object)

    return result_list